version: 2

models:
    - name: runtime_testing
      columns:
        - name: foo

    - name: generic_testing
      columns:
        - name: foo
          tests:
            - spec:
                predicate: "{{ and(even(), belongs_to([2, 3, 4])) }}"
        - name: bar
          tests:
            - spec:
                predicate: >-
                  {{
                    keys(
                      required=['A'],
                      optional=['B']
                    )
                  }}
            - spec_fails:
                predicate: >-
                  {{
                    keys(
                      required=['A'],
                      optional=['B'],
                      closed=True
                    )
                  }}
